# Specify a base image
FROM node:16-alpine 

WORKDIR '/app'
# Install some dependencies
# copy everthing in our SIMPLE_WEB_APP to our current container
COPY package.json  .
RUN npm install
## copy all the source code
COPY . .

# Default command
CMD [ "npm", "run", "start" ]